name: Build Packages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - shell: bash
        run: |
          pnpm install --no-frozen-lockfile
          pnpm install --no-frozen-lockfile --prod

  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      examples: ${{ steps.list-examples.outputs.examples }}
    steps:
      - uses: actions/checkout@v4
      - name: List examples
        id: list-examples
        run: |
          echo "examples=$(ls -d examples/*/ | xargs -n 1 basename | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build-examples:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: ${{ fromJSON(needs.generate-matrix.outputs.examples) }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - shell: bash
        run: |
          pnpm install --no-frozen-lockfile
          cd examples/${{ matrix.example }}
          pnpm build
