name: Add issues to Project Management dashboard
on:
  issues:
    types:
      - opened
      - reopened
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/orgs/topology-gg/projects/1
          github-token: ${{ secrets.TOPOLOGY_PAT }}
