name: Test Packages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - shell: bash
        run: |
          pnpm install --no-frozen-lockfile

      - shell: bash
        run: |
          pnpm test

      - shell: bash
        run: |
          pnpm run coverage
      - name: "Report coverage"
        uses: davelosert/vitest-coverage-report-action@v2
